# Generated by Django 3.2.3 on 2021-06-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
    ]
