# Generated by Django 3.2.3 on 2021-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsite', '0003_alter_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
