# Generated by Django 3.2.3 on 2021-07-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsite', '0004_user_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='アイコン'),
        ),
    ]
